name: wireguard_kit
version: 0.5.0
description: >
  WireGuard for iOS and macOS

  This project contains an application for iOS and for macOS, as well as many components shared between the two of them.
  You may toggle between the two platforms by selecting the target from within Xcode.
homepage: https://nettica.com
license: MIT
authors:
  - Nettica Development

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: WireGuardKit
        podspec: WireGuardKit.podspec
      macos:
        pluginClass: WireGuardKit
        podspec: WireGuardKit.podspec

  assets:
    - Sources/WireGuardKitC/
    - Sources/WireGuardKit/
    - Sources/Shared/
    - Sources/WireGuardKitGo/wireguard.h
    - Sources/WireGuardNetworkExtension/